### ISSUE TITLE
Offline calibration of raw gaze data

### ISSUE THREAD

**Issue by vahid-sb** [labstreaminglayer/App-Tobii#1]
Hi guys
This is not an issue with your code, rather a question. Do you know of an open-source code that can be used to apply the claibration data collected in Tobii Pro Lab and apply it to the raw gaze data collected using the LSL app (when calibratoin is not incorporated as a config file)? I checked the Tobii SDK and it only seem to work in real-time. And have not been able to find one that fits this purpose so far. 
Regards,
Vahid

**Comment by cboulay** [comment]
Hi Vahid. I'm sorry no one was able to answer you. This repo is rather outdated. In fact, I am closing this issue because I am archiving the repo.
You may wish to check the App-TobiiPro repo instead.
